app:
  candidate:
    name: "L Shravya"
    email: "shravya.l2022@vitstudent.ac.in"
    regNo: "22BCE0804"
  endpoints:
    generateWebhook: "https://bfhldevapigw.healthrx.co.in/hiring/generateWebhook/JAVA"
    testWebhook: "https://bfhldevapigw.healthrx.co.in/hiring/testWebhook/JAVA"

spring:
  main:
    web-application-type: none # no web server needed
logging:
  level:
    root: INFO
    com.example.bfh: INFO
